// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIvnkxzU9fKCMqdvJYyPkIcQEILi0HjE',
    appId: '1:691232249929:web:1ef0d8c6171899a3d68798',
    messagingSenderId: '691232249929',
    projectId: 'mynotes-project-2023',
    authDomain: 'mynotes-project-2023.firebaseapp.com',
    storageBucket: 'mynotes-project-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8qlwStPySM7Ub-StF4uGAL6DIf6w31w',
    appId: '1:691232249929:android:095718d341b7691cd68798',
    messagingSenderId: '691232249929',
    projectId: 'mynotes-project-2023',
    storageBucket: 'mynotes-project-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvp_Pgoy-iwWOSFyX6KwkL72ZPnAuwgo',
    appId: '1:691232249929:ios:e01b8231112aaeb8d68798',
    messagingSenderId: '691232249929',
    projectId: 'mynotes-project-2023',
    storageBucket: 'mynotes-project-2023.appspot.com',
    iosClientId: '691232249929-8ahgvkl9m6jq1mncc1amgdr5sd66oin0.apps.googleusercontent.com',
    iosBundleId: 'com.test.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvp_Pgoy-iwWOSFyX6KwkL72ZPnAuwgo',
    appId: '1:691232249929:ios:dcfe5171c70f8423d68798',
    messagingSenderId: '691232249929',
    projectId: 'mynotes-project-2023',
    storageBucket: 'mynotes-project-2023.appspot.com',
    iosClientId: '691232249929-5b3qrpd4kqhc4qug9qb97f94cmlu1d39.apps.googleusercontent.com',
    iosBundleId: 'com.test.mynotes.RunnerTests',
  );
}
